In [2]:
ban=0
batch_size=4

In [3]:
import torch

device0 = torch.device('cuda:5' if torch.cuda.is_available() else "cpu")
device1 = torch.device('cuda:5' if torch.cuda.is_available() else "cpu")

In [4]:
# 读数据
import pandas as pd
df_train=pd.read_excel("../data/df_train.xlsx",index_col=0)
df_test=pd.read_excel("../data/df_test.xlsx",index_col=0)

In [5]:
for i in range(len(df_train)):
    print(df_train.loc[i])
    break

text     天空下着暴雨，*正在给c1穿雨衣，他自己却只穿着单薄的军装，完全暴露在大雨之中。
label                          [0, 0, 0, 0, 0, 0]
Name: 0, dtype: object


In [6]:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("bert-base-chinese")
df_train_text=[df_train['text'][i] for i in range(len(df_train))]

In [7]:
text2id_train = tokenizer(
        df_train_text, max_length=100, padding='max_length', truncation=True, return_tensors="pt"
    )
input_ids_train=text2id_train["input_ids"]
mask_train=text2id_train["attention_mask"]

In [30]:
input_ids_train=input_ids_train.to(device0)
mask_train=input_ids_train.to(device0)

In [19]:
i=3
print(df_train_text[i],input_ids_train[i])#115 *

o2一手拿着一个行李，一路小跑着把*带到了文工团门口。 tensor([ 101,  157, 8144,  671, 2797, 2897, 4708,  671,  702, 6121, 3330, 8024,
         671, 6662, 2207, 6651, 4708, 2828,  115, 2372, 1168,  749, 3152, 2339,
        1730, 7305, 1366,  511,  102,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0])


In [20]:
from transformers import AutoTokenizer, AutoModel
model = AutoModel.from_pretrained("bert-base-chinese")

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertModel: ['cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [21]:
model=model.to(device0)

In [27]:
print(df_train_text[i],input_ids_train[i])#115 *
print(mask_train[i])#115 *

o2一手拿着一个行李，一路小跑着把*带到了文工团门口。 tensor([ 101,  157, 8144,  671, 2797, 2897, 4708,  671,  702, 6121, 3330, 8024,
         671, 6662, 2207, 6651, 4708, 2828,  115, 2372, 1168,  749, 3152, 2339,
        1730, 7305, 1366,  511,  102,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0])
torch.Size([100])


In [49]:
i=3
print(df_train_text[i])
for ids in input_ids_train[i]:
    print(tokenizer.decode(ids),end=' ')
ee=model(input_ids_train[i].view(1,-1), attention_mask=mask_train[i].view(1,-1))
# print(ee)
print(ee[0][0][3])

o2一手拿着一个行李，一路小跑着把*带到了文工团门口。
[CLS] o ##2 一 手 拿 着 一 个 行 李 ， 一 路 小 跑 着 把 * 带 到 了 文 工 团 门 口 。 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] tensor([ 1.6176e-01, -5.7589e-01, -4.1629e-01,  1.8868e-01, -6.9119e-01,
        -1.4571e-01,  8.1848e-01, -1.6463e-01, -9.6849e-01,  8.0588e-01,
         2.1206e-01, -4.0109e-01, -1.7737e-01, -4.8739e-01,  8.7368e-01,
         5.7747e-01,  3.1207e-01, -2.9949e-01,  7.5629e-01, -6.8908e-02,
         9.7767e-01,  1.1904e+00,  1.8328e-01, -6.5416e-01,  3.4930e-01,
        -2.3717e-01,  4.6956e-01, -2.5943e-01, -2.0320e-01,  3.4010e-02,
        -2.0179e-01, -2.2876e-02,  6.909

In [51]:
i=2
print(df_train_text[i])
for ids in input_ids_train[i]:
    print(tokenizer.decode(ids),end=' ')
ee=model(input_ids_train[i].view(1,-1), attention_mask=mask_train[i].view(1,-1))
print(ee[0][0][2])

*一手拿着一个行李，一路小跑着把c1带到了文工团门口。
[CLS] * 一 手 拿 着 一 个 行 李 ， 一 路 小 跑 着 把 c1 带 到 了 文 工 团 门 口 。 [SEP] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] [PAD] tensor([-9.4848e-01,  1.1805e-01, -4.0959e-01,  5.3761e-01,  3.8722e-01,
        -6.9740e-01, -8.5211e-01,  1.2992e+00,  2.1928e-01,  5.3818e-01,
         4.6333e-01, -6.6036e-01,  1.3441e+00, -1.0664e+00, -4.1901e-01,
         2.0003e-01,  3.9185e-01,  5.7158e-01, -2.5513e-01,  4.3548e-01,
         8.4873e-01,  1.4879e+00,  8.4059e-01, -4.0989e-01, -1.4731e-01,
         7.5528e-01, -5.5838e-02, -2.1050e+00, -8.4114e-03,  6.4950e-01,
        -2.5560e-01,  5.3908e-01,  2.

In [ ]:
from transformers import AutoTokenizer, AutoModel
import torch.nn as nn
import torch.nn.functional as F


class fn_cls(nn.Module):
    def __init__(self,device):
        super(fn_cls, self).__init__()
        self.model = AutoModel.from_pretrained("bert-base-chinese")
        self.model.to(device)
        self.dropout = nn.Dropout(0.5)
        self.l1 = nn.Linear(768, 18)

    def forward(self, x, attention_mask=None):
        outputs = self.model(x, attention_mask=attention_mask)
        x = outputs[0]#batch size* 100 * 768
        x = self.dropout(x)
        x = self.l1(x)
        return x

In [63]:
def get_att(input_ids_train_):
    index=0
    _115=[]
    for i in input_ids_train_:
        if i==115:
#             print(i)
            _115.append(index)
        index+=1
    ###########################################################
    att=[]

    index=0
    max_=0
    for i in input_ids_train[i]:
        if i in [101,102,0]:
            att.append(-1)
            index+=1
            continue
        att_t=[]
        for j in _115:
            att_t.append(abs(index-j))


        att.append(min(att_t))
        if min(att_t)>max_:
            max_=min(att_t)

        index+=1
#     print(att)
    ###########################################################
    att0=[]
    for j in att:
        if j==-1:
            att0.append(0)
        else:
            att0.append((max_-j)/max_)
#     print(att0)
    return att0

print(get_att(input_ids_train[i]),len(get_att(input_ids_train[i])))

[0, 0.7741935483870968, 0.8064516129032258, 0.8387096774193549, 0.8709677419354839, 0.9032258064516129, 0.9354838709677419, 0.967741935483871, 1.0, 0.967741935483871, 0.9354838709677419, 0.9032258064516129, 0.8709677419354839, 0.8387096774193549, 0.8064516129032258, 0.7741935483870968, 0.7419354838709677, 0.7096774193548387, 0.6774193548387096, 0.6451612903225806, 0.6129032258064516, 0.5806451612903226, 0.5483870967741935, 0.5161290322580645, 0.4838709677419355, 0.45161290322580644, 0.41935483870967744, 0.3870967741935484, 0.3548387096774194, 0.3225806451612903, 0.2903225806451613, 0.25806451612903225, 0.22580645161290322, 0.1935483870967742, 0.16129032258064516, 0.12903225806451613, 0.0967741935483871, 0.06451612903225806, 0.03225806451612903, 0.0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] 100


In [68]:
a = torch.ones(2,4,6)
a

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

In [93]:
b=torch.rand(2,4)
b

tensor([[0.8240, 0.6485, 0.9352, 0.1248],
        [0.6806, 0.9089, 0.7867, 0.5594]])

In [102]:
all_e=[]
for i in range(len(b)):
    bb=b[i]
    aa=a[i]
    print(bb.view(4,1))
    print(aa)
    cc=aa*bb.view(4,1)
    print(cc)
    print(torch.sum(cc,0))
    all_e.append(torch.sum(cc,0))
print(torch.stack(all_e))

tensor([[0.8240],
        [0.6485],
        [0.9352],
        [0.1248]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0.8240, 0.8240, 0.8240, 0.8240, 0.8240, 0.8240],
        [0.6485, 0.6485, 0.6485, 0.6485, 0.6485, 0.6485],
        [0.9352, 0.9352, 0.9352, 0.9352, 0.9352, 0.9352],
        [0.1248, 0.1248, 0.1248, 0.1248, 0.1248, 0.1248]])
tensor([2.5325, 2.5325, 2.5325, 2.5325, 2.5325, 2.5325])
tensor([[0.6806],
        [0.9089],
        [0.7867],
        [0.5594]])
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])
tensor([[0.6806, 0.6806, 0.6806, 0.6806, 0.6806, 0.6806],
        [0.9089, 0.9089, 0.9089, 0.9089, 0.9089, 0.9089],
        [0.7867, 0.7867, 0.7867, 0.7867, 0.7867, 0.7867],
        [0.5594, 0.5594, 0.5594, 0.5594, 0.5594, 0.5594]])
tensor([2.9355, 2.9355, 2.9355, 2.9355, 2.9355, 2.9355])


In [2]:
import torch
a = torch.ones(2,6)
a

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [1]:
import torch
b = torch.rand(2)
b

tensor([0.8189, 0.7499])

In [6]:
c=a/b.t()

RuntimeError: The size of tensor a (6) must match the size of tensor b (2) at non-singleton dimension 1

In [12]:
import torch.nn as nn
b = torch.rand(24)
print(b)
b0=b.split(4, 0)
print(b0)
b0=torch.stack(b0)
print(b0)
f = nn.Softmax(dim = 1) 
b1 = f(b0)
print(b1)

tensor([0.0555, 0.6183, 0.0394, 0.9393, 0.7659, 0.9817, 0.2645, 0.7399, 0.4441,
        0.0349, 0.8468, 0.5814, 0.3220, 0.6193, 0.5564, 0.0424, 0.9073, 0.1680,
        0.1592, 0.5378, 0.9052, 0.0583, 0.7725, 0.3413])
(tensor([0.0555, 0.6183, 0.0394, 0.9393]), tensor([0.7659, 0.9817, 0.2645, 0.7399]), tensor([0.4441, 0.0349, 0.8468, 0.5814]), tensor([0.3220, 0.6193, 0.5564, 0.0424]), tensor([0.9073, 0.1680, 0.1592, 0.5378]), tensor([0.9052, 0.0583, 0.7725, 0.3413]))
tensor([[0.0555, 0.6183, 0.0394, 0.9393],
        [0.7659, 0.9817, 0.2645, 0.7399],
        [0.4441, 0.0349, 0.8468, 0.5814],
        [0.3220, 0.6193, 0.5564, 0.0424],
        [0.9073, 0.1680, 0.1592, 0.5378],
        [0.9052, 0.0583, 0.7725, 0.3413]])
tensor([[0.1624, 0.2850, 0.1597, 0.3929],
        [0.2617, 0.3248, 0.1585, 0.2550],
        [0.2322, 0.1542, 0.3473, 0.2663],
        [0.2290, 0.3083, 0.2895, 0.1732],
        [0.3785, 0.1807, 0.1791, 0.2616],
        [0.3480, 0.1492, 0.3048, 0.1980]])


In [26]:
import torch.nn as nn
x = torch.rand((3,24))
print(x)
end=[]
for i in range(len(x)):
    end.append(torch.stack(list(x[i].split(4, 0))))
x=torch.stack(end)
print(x)
# b0=torch.stack
# print(b0)

tensor([[0.2711, 0.8774, 0.0171, 0.2485, 0.1644, 0.9675, 0.1289, 0.2879, 0.1195,
         0.3633, 0.2045, 0.3651, 0.9948, 0.1026, 0.8682, 0.8488, 0.1908, 0.5127,
         0.2769, 0.1463, 0.2324, 0.4461, 0.0231, 0.6756],
        [0.0144, 0.5674, 0.1124, 0.1504, 0.7175, 0.6074, 0.3690, 0.9623, 0.4468,
         0.8777, 0.1288, 0.8800, 0.9503, 0.4536, 0.5544, 0.0623, 0.0066, 0.2780,
         0.7880, 0.0166, 0.3709, 0.5500, 0.8775, 0.9782],
        [0.9852, 0.2740, 0.5605, 0.4627, 0.1488, 0.4740, 0.4224, 0.1127, 0.7800,
         0.6065, 0.3646, 0.9855, 0.9512, 0.8349, 0.6152, 0.0999, 0.4404, 0.0929,
         0.6295, 0.0685, 0.8393, 0.8998, 0.4601, 0.9306]])
tensor([[[0.2711, 0.8774, 0.0171, 0.2485],
         [0.1644, 0.9675, 0.1289, 0.2879],
         [0.1195, 0.3633, 0.2045, 0.3651],
         [0.9948, 0.1026, 0.8682, 0.8488],
         [0.1908, 0.5127, 0.2769, 0.1463],
         [0.2324, 0.4461, 0.0231, 0.6756]],

        [[0.0144, 0.5674, 0.1124, 0.1504],
         [0.7175, 0.6074, 0.3690, 0.